### ISSUE TITLE
Use custom field labels on configuration form

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.moregreetings#10]
Instead of just showing "Greeting X" on the configuration form, the custom field labels should be used as labels for the configuration fields, so that the greeting configuration is better identifiable.

**Comment by bjendres** [comment]
@jensschuppe is this save enough to go into ``1.1`` or does that require more testing/updates?

**Comment by jensschuppe** [comment]
I can't really remember but the code is just adding a string from the custom field, so testing this is a no-brainer.

**Comment by jensschuppe** [comment]
This has been released with version 1.2.0-beta1
