### ISSUE TITLE
French orthograph is wrong

### ISSUE THREAD

**Issue by Dev-AllInAppli** [systopia/de.systopia.moregreetings#17]
In the [fr_greeting.tpl](https://github.com/systopia/de.systopia.moregreetings/blob/master/examples/fr_greeting.tpl), there are words to correct.
I could do this if needed.
Guillaume

**Comment by jensschuppe** [comment]
Thanks for reporting @Dev-AllInAppli. Feel free to make a PR.

**Comment by jensschuppe** [comment]
Fixed in #18, thanks @Dev-AllInAppli!
