### ISSUE TITLE
More Greeting not found in the navigation

### ISSUE THREAD

**Issue by mvharlan** [systopia/de.systopia.moregreetings#41]
Hi,

just installed the "More Greetings" extension, but could not find it in the menu tree. Navigation finder couldn't find it either. So I cannot configure it.

Thanx, Magnus

**Comment by bjendres** [comment]
The MoreGreetings configuration is listed in the administration area (``civicrm/admin?reset=1``) under "More Greetings" (``civicrm/admin/setting/moregreetings?reset=1``). You'll need administrator privileges to access/configure that.

**Comment by jensschuppe** [comment]
Actually, there should be a navigation menu item since version `1.2.0-beta1`, see #32. It's located in *Administration* » *Communications*
